[package]
name = "fakerator"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-core = "0.3.28"
fakerator-macros = { path = "macros" }
pin-project = "1.1.0"

[workspace]
members = [
    ".",
    "macros",
]

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
tokio = { version = "1.0", features = [ "test-util", "macros" ] }
