[package]
name = "genawaiter"
version = "0.1.0"
edition = "2021"

[dependencies]
genawaiter-macros = { path = "macros" }

[workspace]
members = [
    ".",
    "macros",
]

[build-dependencies]
rustc_version = "0.4.0"
