[workspace]
members = [
    ".",
    "macros",
]

[package]
name = "fauxgen"
version = "0.1.0"
edition = "2021"

[features]
std-generators = []

[dependencies]
futures-core = "0.3"
fauxgen-macros = { path = "macros" }

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
futures-util = "0.3.28"
pin-project = "1.1.0"
tokio = { version = "1.0", features = [ "test-util", "macros" ] }

[profile.release]
lto = "fat"
